### ISSUE TITLE
Rename cmdlets

### ISSUE THREAD

**Issue by schefDev** [dfensgmbh/biz.dfch.PS.Activiti.Client#2]
Remove-WorkflowInstance to Stop-WorkflowInstance
Invoke-WorkflowInstance to Start-WorkflowInstance
(new Pause-WorkflowInstance, Resume-WorkflowInstance)

**Comment by schefDev** [comment]
Start- / Stop-WorkflowInstance already renamed

**Comment by dfch** [comment]
@schefDev can this issue be closed? if not , what is still open? and when can we expect a release for it?

**Comment by schefDev** [comment]
Pause-WorkflowInstance, Resume-WorkflowInstance cmdlets make absolutely no sense (not available at activiti api)
